version: '2'

services:
    db:
        image: postgres
        hostname: db
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        ports:
            - "5432:5432"


    redis:
        image: redis:2.8.19
        hostname: redis


    rabbit:
        hostname: rabbit
        image: rabbitmq:3.6.0
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=mypass
        ports:
            - "5672:5672"  # we forward this port because it's useful for debugging
            - "15672:15672"  # here, we can access rabbitmq management plugin


    master:
        build:
            context: .
        dockerfile: Dockerfile
        hostname: master
        command: ./run_master.sh
        volumes:
            - .:/app  # mount current directory inside container
        links:
            - db
            - rabbit
            - redis
        depends_on:
            - db


    worker:
        build:
            context: .
        dockerfile: Dockerfile
        command: ./run_worker.sh
        volumes:
            - .:/app
        links:
            - db
            - rabbit
            - redis
        depends_on:
            - rabbit
