version: '2'

services:
    rabbit:
        hostname: rabbit
        image: rabbitmq:3.6.0
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=mypass
        ports:
            - "5672:5672"  # we forward this port because it's useful for debugging
            - "15672:15672"  # here, we can access rabbitmq management plugin


    master_node:
        build:
            context: .
            dockerfile: Dockerfile
        hostname: master
        command: ./run_master.sh
        volumes:
            - .:/app  # mount current directory inside container
        links:
            - rabbit
        depends_on:
            - rabbit


    worker_node:
        build:
            context: .
            dockerfile: Dockerfile
        command: ./run_worker.sh
        volumes:
            - .:/app
        links:
            - rabbit
        depends_on:
            - rabbit
